# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alicia Ge
name: Alicia Ge
email: example@gmail.com
location: Ann Arbor, MI, US
company: Banyan
company_url: https://www.banyanbbt.org
github_url: https://github.com/G-bgyl
description: This is personnel website of Alicia Ge
favicon: favicon.png # Image must be in assets/images

url: https://g-bgyl.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show


# For about.html. Fell free to create your own!
skill_software_keywords: [Python, MySQL, Oracle, SQLite, Design Patterns]
skill_data_science_keywords: [Machine Learning, Tensorflow, NLP]
skill_data_analytics_keywords: [Pandas, R]
